### ISSUE TITLE
[Bug] Occasional exceptions when Bambu Studio triggers a push all/get version

### ISSUE THREAD

**Issue by AdrianGarside** [greghesp/ha-bambulab#122]
### Describe the bug

2023-04-24 20:06:19.737 DEBUG (Thread-2 (listen_thread)) [custom_components.bambu_lab.pybambu] Got Version Command Data
2023-04-24 20:06:19.737 DEBUG (Thread-2 (listen_thread)) [custom_components.bambu_lab.pybambu] Device is P1P
2023-04-24 20:06:20.138 DEBUG (MainThread) [custom_components.bambu_lab] async_forward_entry_unload
2023-04-24 20:06:20.138 DEBUG (MainThread) [custom_components.bambu_lab] async_forward_entry_unload
2023-04-24 20:06:20.138 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry SERIAL for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 539, in async_unload
    result = await component.async_unload_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 137, in async_unload_entry
    return await component.async_unload_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 181, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
2023-04-24 20:06:20.139 DEBUG (MainThread) [custom_components.bambu_lab] async_forward_entry_setup
2023-04-24 20:06:20.140 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.bambu_lab
2023-04-24 20:06:20.143 DEBUG (MainThread) [custom_components.bambu_lab] async_forward_entry_setup
2023-04-24 20:06:20.143 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry SERIAL for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 131, in async_setup_entry
    return await component.async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 166, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
2023-04-24 20:06:20.145 DEBUG (MainThread) [custom_components.bambu_lab] _reinitialize_sensors DONE
2023-04-24 20:06:20.145 DEBUG (MainThread) [custom_components.bambu_lab] _reinitialize_sensors DONE

### To Reproduce

Not clear - it doesn't remotely happen reliably.

### Expected Behaviour

No exceptions.

### What device are you using?

P1P

### Firmware Version

Latest

### Home Assistant Version

2023.3.6

### Component Version

1.1.2

**Comment by AdrianGarside** [comment]
Looks like this occurs when we have two sensor refreshes running in parallel:
2023-04-24 20:06:20.138 DEBUG (MainThread) [custom_components.bambu_lab] async_forward_entry_unload
2023-04-24 20:06:20.138 DEBUG (MainThread) [custom_components.bambu_lab] async_forward_entry_unload
...
2023-04-24 20:06:20.145 DEBUG (MainThread) [custom_components.bambu_lab] _reinitialize_sensors DONE
2023-04-24 20:06:20.145 DEBUG (MainThread) [custom_components.bambu_lab] _reinitialize_sensors DONE

**Comment by AdrianGarside** [comment]
Fixed in 1.4.2-dev
