### ISSUE TITLE
[Bug] RuntimeError: Event loop is closed causing HA to crash after a few hours

### ISSUE THREAD

**Issue by tretabyte** [greghesp/ha-bambulab#166]
### Describe the bug

HA is running fine but all the sudden the integration starts to write lots of logging, we can see several _RuntimeError: Event loop is closed_ errors and after a few minutes HA crashes, the only way I found to recover from it is to force a VM reboot to the machine and then delete the integration

### To Reproduce

Let it run normally
while HA and a print is running, the integration starts to write a log of errors in logs
after a couple of minutes we start seeing RuntimeError: Event loop is closed
HA crashes a few minutes later

### Expected Behaviour

Running without causing a crash on HA

### What device are you using?

X1C

### Firmware Version

01.05.02.00, AMS 00.00.06.32

### Home Assistant Version

 Home Assistant 2023.7.3, Supervisor 2023.07.1, Operating System 10.3

### Component Version

v1.4.6

### Log Extracts
```
2023-07-23 20:45:45.115 ERROR (Thread-17 (listen_thread)) [custom_components.bambu_lab.pybambu] An exception occurred processing a message:
2023-07-23 20:45:45.255 ERROR (Thread-17 (listen_thread)) [custom_components.bambu_lab.pybambu] Exception type: <class 'RuntimeError'>
2023-07-23 20:45:45.256 ERROR (Thread-17 (listen_thread)) [custom_components.bambu_lab.pybambu] Exception args: ('list changed size during iteration',)
2023-07-23 21:28:13.319 ERROR (MainThread) [homeassistant.components.sensor] Platform bambu_lab does not generate unique IDs. ID X1C_00M0XXXXXXXXXX_ExternalSpool_external_spool already exists - ignoring sensor.x1c_00m0XXXXXXXXXX_externalspool_external_spool
2023-07-23 21:28:13.322 ERROR (MainThread) [homeassistant.components.sensor] Platform bambu_lab does not generate unique IDs. ID X1C_00M0XXXXXXXXXX_AMS_00600XXXXXXXXXX_humidity_index already exists - ignoring sensor.x1c_00m0XXXXXXXXXX_ams_1_humidity_index
2023-07-23 21:28:13.323 ERROR (MainThread) [homeassistant.components.sensor] Platform bambu_lab does not generate unique IDs. ID X1C_00M0XXXXXXXXXX_AMS_00600XXXXXXXXXX_temperature already exists - ignoring sensor.x1c_00m0XXXXXXXXXX_ams_1_temperature
2023-07-23 21:28:13.325 ERROR (MainThread) [homeassistant.components.sensor] Platform bambu_lab does not generate unique IDs. ID X1C_00M0XXXXXXXXXX_AMS_00600XXXXXXXXXX_tray_1 already exists - ignoring sensor.x1c_00m0XXXXXXXXXX_ams_1_tray_1
2023-07-23 21:28:13.327 ERROR (MainThread) [homeassistant.components.sensor] Platform bambu_lab does not generate unique IDs. ID X1C_00M0XXXXXXXXXX_AMS_00600XXXXXXXXXX_tray_2 already exists - ignoring sensor.x1c_00m0XXXXXXXXXX_ams_1_tray_2
2023-07-23 21:28:13.328 ERROR (MainThread) [homeassistant.components.sensor] Platform bambu_lab does not generate unique IDs. ID X1C_00M0XXXXXXXXXX_AMS_00600XXXXXXXXXX_tray_3 already exists - ignoring sensor.x1c_00m0XXXXXXXXXX_ams_1_tray_3
2023-07-23 21:28:13.333 ERROR (MainThread) [homeassistant.components.sensor] Platform bambu_lab does not generate unique IDs. ID X1C_00M0XXXXXXXXXX_AMS_00600XXXXXXXXXX_tray_4 already exists - ignoring sensor.x1c_00m0XXXXXXXXXX_ams_1_tray_4
2023-07-23 21:28:13.335 ERROR (MainThread) [homeassistant.components.sensor] Platform bambu_lab does not generate unique IDs. ID 00M0XXXXXXXXXX_wifi_signal already exists - ignoring sensor.x1c_00m0XXXXXXXXXX_wi_fi_signal
2023-07-23 21:28:13.349 ERROR (MainThread) [homeassistant.components.sensor] Platform bambu_lab does not generate unique IDs. ID 00M0XXXXXXXXXX_bed_temp already exists - ignoring sensor.x1c_00m0XXXXXXXXXX_bed_temperature
2023-07-23 21:28:13.351 ERROR (MainThread) [homeassistant.components.sensor] Platform bambu_lab does not generate unique IDs. ID 00M0XXXXXXXXXX_target_bed_temp already exists - ignoring sensor.x1c_00m0XXXXXXXXXX_target_bed_temperature
2023-07-23 21:28:13.353 ERROR (MainThread) [homeassistant.components.sensor] Platform bambu_lab does not generate unique IDs. ID 00M0XXXXXXXXXX_chamber_temp already exists - ignoring sensor.x1c_00m0XXXXXXXXXX_chamber_temperature
2023-07-23 21:28:13.358 ERROR (MainThread) [homeassistant.components.sensor] Platform bambu_lab does not generate unique IDs. ID 00M0XXXXXXXXXX_target_nozzle_temp already exists - ignoring sensor.x1c_00m0XXXXXXXXXX_nozzle_target_temperature
2023-07-23 21:28:13.360 ERROR (MainThread) [homeassistant.components.sensor] Platform bambu_lab does not generate unique IDs. ID 00M0XXXXXXXXXX_nozzle_temp already exists - ignoring sensor.x1c_00m0XXXXXXXXXX_nozzle_temperature
2023-07-23 21:28:13.370 ERROR (MainThread) [homeassistant.components.sensor] Platform bambu_lab does not generate unique IDs. ID 00M0XXXXXXXXXX_aux_fan_speed already exists - ignoring sensor.x1c_00m0XXXXXXXXXX_aux_fan_speed
2023-07-23 21:28:13.373 ERROR (MainThread) [homeassistant.components.sensor] Platform bambu_lab does not generate unique IDs. ID 00M0XXXXXXXXXX_chamber_fan_speed already exists - ignoring sensor.x1c_00m0XXXXXXXXXX_chamber_fan_speed
2023-07-23 21:28:13.375 ERROR (MainThread) [homeassistant.components.sensor] Platform bambu_lab does not generate unique IDs. ID 00M0XXXXXXXXXX_cooling_fan_speed already exists - ignoring sensor.x1c_00m0XXXXXXXXXX_cooling_fan_speed
2023-07-23 21:28:13.376 ERROR (MainThread) [homeassistant.components.sensor] Platform bambu_lab does not generate unique IDs. ID 00M0XXXXXXXXXX_heatbreak_fan_speed already exists - ignoring sensor.x1c_00m0XXXXXXXXXX_heatbreak_fan_speed
2023-07-23 21:28:13.380 ERROR (MainThread) [homeassistant.components.sensor] Platform bambu_lab does not generate unique IDs. ID 00M0XXXXXXXXXX_speed_profile already exists - ignoring sensor.x1c_00m0XXXXXXXXXX_speed_profile
2023-07-23 21:28:13.382 ERROR (MainThread) [homeassistant.components.sensor] Platform bambu_lab does not generate unique IDs. ID 00M0XXXXXXXXXX_stage already exists - ignoring sensor.x1c_00m0XXXXXXXXXX_current_stage
2023-07-23 21:28:13.384 ERROR (MainThread) [homeassistant.components.sensor] Platform bambu_lab does not generate unique IDs. ID 00M0XXXXXXXXXX_print_progress already exists - ignoring sensor.x1c_00m0XXXXXXXXXX_print_progress
2023-07-23 21:28:13.387 ERROR (MainThread) [homeassistant.components.sensor] Platform bambu_lab does not generate unique IDs. ID 00M0XXXXXXXXXX_print_status already exists - ignoring sensor.x1c_00m0XXXXXXXXXX_print_status
2023-07-23 21:28:13.389 ERROR (MainThread) [homeassistant.components.sensor] Platform bambu_lab does not generate unique IDs. ID 00M0XXXXXXXXXX_start_time already exists - ignoring sensor.x1c_00m0XXXXXXXXXX_start_time
2023-07-23 21:28:13.390 ERROR (MainThread) [homeassistant.components.sensor] Platform bambu_lab does not generate unique IDs. ID 00M0XXXXXXXXXX_remaining_time already exists - ignoring sensor.x1c_00m0XXXXXXXXXX_remaining_time
2023-07-23 21:28:13.392 ERROR (MainThread) [homeassistant.components.sensor] Platform bambu_lab does not generate unique IDs. ID 00M0XXXXXXXXXX_end_time already exists - ignoring sensor.x1c_00m0XXXXXXXXXX_end_time
2023-07-23 21:28:13.399 ERROR (MainThread) [homeassistant.components.sensor] Platform bambu_lab does not generate unique IDs. ID 00M0XXXXXXXXXX_current_layer already exists - ignoring sensor.x1c_00m0XXXXXXXXXX_current_layer
2023-07-23 21:28:13.400 ERROR (MainThread) [homeassistant.components.sensor] Platform bambu_lab does not generate unique IDs. ID 00M0XXXXXXXXXX_total_layers already exists - ignoring sensor.x1c_00m0XXXXXXXXXX_total_layer_count
2023-07-23 21:28:13.400 ERROR (MainThread) [homeassistant.components.sensor] Platform bambu_lab does not generate unique IDs. ID 00M0XXXXXXXXXX_tray_now already exists - ignoring sensor.x1c_00m0XXXXXXXXXX_active_tray
2023-07-23 22:29:06.406 ERROR (Thread-17 (listen_thread)) [custom_components.bambu_lab.pybambu] An exception occurred processing a message:
2023-07-23 22:29:06.407 ERROR (Thread-17 (listen_thread)) [custom_components.bambu_lab.pybambu] Exception type: <class 'RuntimeError'>
2023-07-23 22:29:06.408 ERROR (Thread-17 (listen_thread)) [custom_components.bambu_lab.pybambu] Exception args: ('Event loop is closed',)
2023-07-23 22:29:07.092 ERROR (stream_worker) [root] Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/src/homeassistant/homeassistant/components/stream/__init__.py", line 424, in _run_worker
    stream_worker(
  File "/usr/src/homeassistant/homeassistant/components/stream/worker.py", line 624, in stream_worker
    muxer.mux_packet(packet)
  File "/usr/src/homeassistant/homeassistant/components/stream/worker.py", line 265, in mux_packet
    self.check_flush_part(packet)
  File "/usr/src/homeassistant/homeassistant/components/stream/worker.py", line 304, in check_flush_part
    self.flush(packet, last_part=False)
  File "/usr/src/homeassistant/homeassistant/components/stream/worker.py", line 353, in flush
    self._hass.loop.call_soon_threadsafe(
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 806, in call_soon_threadsafe
    self._check_closed()
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 519, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2023-07-23 22:29:07.392 ERROR (Thread-17 (listen_thread)) [custom_components.bambu_lab.pybambu] An exception occurred processing a message:
2023-07-23 22:29:07.392 ERROR (Thread-17 (listen_thread)) [custom_components.bambu_lab.pybambu] Exception type: <class 'RuntimeError'>
2023-07-23 22:29:07.393 ERROR (Thread-17 (listen_thread)) [custom_components.bambu_lab.pybambu] Exception args: ('Event loop is closed',)
2023-07-23 22:29:08.401 ERROR (Thread-17 (listen_thread)) [custom_components.bambu_lab.pybambu] An exception occurred processing a message:
2023-07-23 22:29:08.403 ERROR (Thread-17 (listen_thread)) [custom_components.bambu_lab.pybambu] Exception type: <class 'RuntimeError'>
2023-07-23 22:29:08.403 ERROR (Thread-17 (listen_thread)) [custom_components.bambu_lab.pybambu] Exception args: ('Event loop is closed',)
2023-07-23 22:29:09.417 ERROR (Thread-17 (listen_thread)) [custom_components.bambu_lab.pybambu] An exception occurred processing a message:
2023-07-23 22:29:09.418 ERROR (Thread-17 (listen_thread)) [custom_components.bambu_lab.pybambu] Exception type: <class 'RuntimeError'>
2023-07-23 22:29:09.419 ERROR (Thread-17 (listen_thread)) [custom_components.bambu_lab.pybambu] Exception args: ('Event loop is closed',)
2023-07-23 22:29:09.718 ERROR (Thread-229 (_thread_main)) [root] Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 3591, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 1756, in loop_forever
    rc = self._loop(timeout)
         ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 1164, in _loop
    rc = self.loop_read()
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 1556, in loop_read
    rc = self._packet_read()
         ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 2439, in _packet_read
    rc = self._packet_handle()
         ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 3033, in _packet_handle
    return self._handle_publish()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 3327, in _handle_publish
    self._handle_on_message(message)
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 3570, in _handle_on_message
    on_message(self, self._userdata, message)
  File "/usr/local/lib/python3.11/site-packages/tuya_iot/openmq.py", line 147, in _on_message
    listener(msg_dict)
  File "/usr/local/lib/python3.11/site-packages/tuya_iot/device.py", line 172, in on_message
    self._on_device_report(data["devId"], data["status"])
  File "/usr/local/lib/python3.11/site-packages/tuya_iot/device.py", line 191, in _on_device_report
    self.__update_device(device)
  File "/usr/local/lib/python3.11/site-packages/tuya_iot/device.py", line 178, in __update_device
    listener.update_device(device)
  File "/usr/src/homeassistant/homeassistant/components/tuya/__init__.py", line 260, in update_device
    dispatcher_send(self.hass, f"{TUYA_HA_SIGNAL_UPDATE_ENTITY}_{device.id}")
  File "/usr/src/homeassistant/homeassistant/helpers/dispatcher.py", line 62, in dispatcher_send
    hass.loop.call_soon_threadsafe(async_dispatcher_send, hass, signal, *args)
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 806, in call_soon_threadsafe
    self._check_closed()
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 519, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2023-07-23 22:29:10.427 ERROR (Thread-17 (listen_thread)) [custom_components.bambu_lab.pybambu] An exception occurred processing a message:
2023-07-23 22:29:10.428 ERROR (Thread-17 (listen_thread)) [custom_components.bambu_lab.pybambu] Exception type: <class 'RuntimeError'>
2023-07-23 22:29:10.431 ERROR (Thread-17 (listen_thread)) [custom_components.bambu_lab.pybambu] Exception args: ('Event loop is closed',)
2023-07-23 22:29:11.453 ERROR (Thread-17 (listen_thread)) [custom_components.bambu_lab.pybambu] An exception occurred processing a message:
2023-07-23 22:29:11.455 ERROR (Thread-17 (listen_thread)) [custom_components.bambu_lab.pybambu] Exception type: <class 'RuntimeError'>
2023-07-23 22:29:11.457 ERROR (Thread-17 (listen_thread)) [custom_components.bambu_lab.pybambu] Exception args: ('Event loop is closed',)
2023-07-23 22:29:12.460 ERROR (Thread-17 (listen_thread)) [custom_components.bambu_lab.pybambu] An exception occurred processing a message:
2023-07-23 22:29:12.461 ERROR (Thread-17 (listen_thread)) [custom_components.bambu_lab.pybambu] Exception type: <class 'RuntimeError'>
2023-07-23 22:29:12.462 ERROR (Thread-17 (listen_thread)) [custom_components.bambu_lab.pybambu] Exception args: ('Event loop is closed',)
2023-07-23 22:29:13.474 ERROR (Thread-17 (listen_thread)) [custom_components.bambu_lab.pybambu] An exception occurred processing a message:
2023-07-23 22:29:13.475 ERROR (Thread-17 (listen_thread)) [custom_components.bambu_lab.pybambu] Exception type: <class 'RuntimeError'>
2023-07-23 22:29:13.475 ERROR (Thread-17 (listen_thread)) [custom_components.bambu_lab.pybambu] Exception args: ('Event loop is closed',)
2023-07-23 22:29:13.484 ERROR (Thread-3 (_thread_main)) [paho.mqtt.client] Caught exception in on_message: Event loop is closed
2023-07-23 22:29:13.487 ERROR (Thread-3 (_thread_main)) [root] Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 3591, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 1756, in loop_forever
    rc = self._loop(timeout)
         ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 1164, in _loop
    rc = self.loop_read()
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 1556, in loop_read
    rc = self._packet_read()
         ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 2439, in _packet_read
    rc = self._packet_handle()
         ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 3033, in _packet_handle
    return self._handle_publish()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 3327, in _handle_publish
    self._handle_on_message(message)
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 3570, in _handle_on_message
    on_message(self, self._userdata, message)
  File "/usr/src/homeassistant/homeassistant/components/mqtt/client.py", line 784, in _mqtt_on_message
    self.hass.add_job(self._mqtt_handle_message, msg)
  File "/usr/src/homeassistant/homeassistant/core.py", line 437, in add_job
    self.loop.call_soon_threadsafe(self.async_add_job, target, *args)
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 806, in call_soon_threadsafe
    self._check_closed()
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 519, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

**Comment by tretabyte** [comment]
seems to have stopped with the latest version
