### ISSUE TITLE
[Bug] When printer turn off and the turn on, the entities integration don't update the status

### ISSUE THREAD

**Issue by josemabcn** [greghesp/ha-bambulab#195]
### Describe the bug

I have a remote switch connected to X1C. The integration is working well, but if I turn OFF the printer, and then turn ON, all the integration entities show the last state before turn off. The light switch for example don't works, I turn the light switch OFF but the light continues ON, etc. I need to go to the integration and reload the integration and then all the entities works well. But If I turn the printer off another time the same problema.

### To Reproduce

Turn off the printer

### Expected Behaviour

When the printer turn ON all the entities needs to be available and working.

### What device are you using?

X1C

### Firmware Version

01.06.03.00

### Home Assistant Version

Supervisor 2023.08.3 / Operating System 10.5 / Frontend 20230908.0 - latest

### Component Version

V1.4.9

**Comment by AdrianGarside** [comment]
That's odd. The logic has been there to detect the printer turning off and then back on again while the integration is running for quite a while. I'll need debug logs from the integration to see if I can work out why this isn't working - there's been no recent changes in this area and it's still working correctly with my P1P.

**Comment by josemabcn** [comment]
I dont' know exactly how to download the depuration log, in the register logs I have the following errors when I try to activate the fans and lights and they don't work:

`ValueError: Sensor sensor.x1c_00m09a360200242_print_status provides state value '', which is not in the list of options provided
2023-09-12 12:13:23.119 ERROR (SyncWorker_10) [custom_components.daily.sensor] unable to convert unavailable to float. Please check the source sensor (sensor.velocidadviento) is available.
2023-09-12 12:13:23.121 ERROR (SyncWorker_10) [custom_components.daily.sensor] unable to convert to float. Please check the source sensor (sensor.velocidadviento) is available.
2023-09-12 12:13:23.241 ERROR (SyncWorker_14) [custom_components.daily.sensor] unable to convert unavailable to float. Please check the source sensor (sensor.velocidadviento) is available.
2023-09-12 12:13:23.242 ERROR (SyncWorker_14) [custom_components.daily.sensor] unable to convert to float. Please check the source sensor (sensor.velocidadviento) is available.
2023-09-12 12:14:07.418 DEBUG (MainThread) [custom_components.bambu_lab] HA POLL: MQTT connected: True
2023-09-12 12:14:07.418 DEBUG (MainThread) [custom_components.bambu_lab] Finished fetching bambu_lab data in 0.000 seconds (success: True)
2023-09-12 12:14:07.419 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 235, in _handle_refresh_interval
await self._async_refresh(log_failures=True, scheduled=True)
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 392, in _async_refresh
self.async_update_listeners()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 173, in async_update_listeners
update_callback()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 473, in _handle_coordinator_update
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 730, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 830, in _async_write_ha_state
state, attr = self._async_generate_attributes()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 771, in _async_generate_attributes
state = self._stringify_state(available)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 736, in _stringify_state
if (state := self.state) is None:
^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 567, in state
raise ValueError(
ValueError: Sensor sensor.x1c_00m09a360200242_print_status provides state value '', which is not in the list of options provided
2023-09-12 12:14:52.058 DEBUG (SyncWorker_2) [custom_components.bambu_lab.pybambu] {'print': {'sequence_id': '0', 'command': 'gcode_line', 'param': 'M106 P2 S255\n'}}
2023-09-12 12:14:52.058 DEBUG (SyncWorker_2) [custom_components.bambu_lab.pybambu] Sent {'print': {'sequence_id': '0', 'command': 'gcode_line', 'param': 'M106 P2 S255\n'}} to topic device/00M09A360200242/request
2023-09-12 12:14:52.571 DEBUG (SyncWorker_10) [custom_components.bambu_lab.pybambu] {'print': {'sequence_id': '0', 'command': 'gcode_line', 'param': 'M106 P3 S255\n'}}
2023-09-12 12:14:52.571 DEBUG (SyncWorker_10) [custom_components.bambu_lab.pybambu] Sent {'print': {'sequence_id': '0', 'command': 'gcode_line', 'param': 'M106 P3 S255\n'}} to topic device/00M09A360200242/request
2023-09-12 12:14:53.647 DEBUG (SyncWorker_2) [custom_components.bambu_lab.pybambu] {'print': {'sequence_id': '0', 'command': 'gcode_line', 'param': 'M106 P1 S255\n'}}
2023-09-12 12:14:53.647 DEBUG (SyncWorker_2) [custom_components.bambu_lab.pybambu] Sent {'print': {'sequence_id': '0', 'command': 'gcode_line', 'param': 'M106 P1 S255\n'}} to topic device/00M09A360200242/request`

**Comment by AdrianGarside** [comment]
@piitaya - this is the root error that appears to then break (most?) other sensors in other reports:

`ValueError: Sensor sensor.x1c_00m09a360200242_print_status provides state value '', which is not in the list of options provided

It seems there's a possible (transient?) state where the mqtt payload hasn't been received or is legitimately sent as empty and if someone hits that the fallout is permanent. I could update sensors that have options to be unavailable if not set to a string so HA will ignore them in the unset state?

**Comment by AdrianGarside** [comment]
@josemabcn please can you give https://github.com/greghesp/ha-bambulab/releases/tag/v1.4.12 a go.

**Comment by josemabcn** [comment]
To check this new version I need to delete in HACS the Bambu Lab integration and install the new version manually?.

**Comment by AdrianGarside** [comment]
No, you can redownload it via HACS here:
![image](https://github.com/greghesp/ha-bambulab/assets/26147576/b70cf106-1ec9-455e-a92f-fb318afe3495)

**Comment by josemabcn** [comment]
Oppsss, I updated by hand with WSCP (sorry, I'm not an expert), after update manually I restarted HA and now is working well. I can turn OFF the printer (disconnect) and when I turn ON the integration discover the state and all the entities works OK.

A lot of thanks Adrian!!!!!

**Comment by Ali229** [comment]
This is still an issue:
![image](https://github.com/greghesp/ha-bambulab/assets/11164440/f3fa9c40-c074-454b-998e-c79193eba4a2)

The printer is turned off for a few hours and it showed 31%, I turned it off AFTER the print was finished, so something happened to the integration when even before the printer was turned off, and since then it's stuck on 31%, I have completely uninstalled the 1.4.8 version and have the 1.4.12. Only reloading the integration works, but I'm guessing it's just short lived.

**Comment by AdrianGarside** [comment]
I need debug log covering the point where it stopped receiving/reacting to data to be able to do anything.

**Comment by Anrolosia** [comment]
Hello @AdrianGarside !
On my side I have the same problem but during the print. And exception is raised and the integration stops updating status. I need to completely reboot my HA.
The only thing I can find in the logs is:
```
2023-09-13 23:06:35.053 ERROR (Thread-17 (listen_thread)) [custom_components.bambu_lab.pybambu] An exception occurred processing a message:
2023-09-13 23:06:35.075 ERROR (Thread-17 (listen_thread)) [custom_components.bambu_lab.pybambu] Exception type: <class 'RuntimeError'>
2023-09-13 23:06:35.077 ERROR (Thread-17 (listen_thread)) [custom_components.bambu_lab.pybambu] Exception args: ('list changed size during iteration',)
```

**Comment by Ali229** [comment]
> I need debug log covering the point where it stopped receiving/reacting to data to be able to do anything.

What is the best way to provide this information without all the bloat from different devices. Sorry I'm still relatively new to home assistant.

**Comment by Ali229** [comment]
Here's what I found when the status stopped updating:
```
2023-09-13 15:44:15.476 ERROR (Thread-4 (listen_thread)) [custom_components.bambu_lab.pybambu] An exception occurred processing a message:
2023-09-13 15:44:15.479 ERROR (Thread-4 (listen_thread)) [custom_components.bambu_lab.pybambu] Exception type: <class 'ValueError'>
2023-09-13 15:44:15.480 ERROR (Thread-4 (listen_thread)) [custom_components.bambu_lab.pybambu] Exception args: ("Sensor sensor.two_print_status provides state value 'pause', which is not in the list of options provided",)
```

For the cameras (this has been on going even when I was on 1.4.8) - Both X1s I have (One and Two) show cameras randomly and then show this error at other times:
```
2023-09-13 15:49:28.685 ERROR (stream_worker) [homeassistant.components.stream.stream.camera.one_camera] Error from stream worker: Error opening stream (ERRORTYPE_5, I/O error) rtsps://****:****@192.168.0.58/streaming/live/1
2023-09-13 15:50:06.041 ERROR (stream_worker) [homeassistant.components.stream.stream.camera.two_camera] Error from stream worker: Error opening stream (ERRORTYPE_5, I/O error) rtsps://****:****@192.168.0.59/streaming/live/1
```

**Comment by piitaya** [comment]
@AdrianGarside Do we have the full list of possible status?
The `device_class` of the sensor is `enum` to be able to have autocompletion in the automation editor to select the state of the sensor.
You have multiple solutions for this issue :
- keep the device class and add the new possible state to the options array.
- remove the device class but we won't be able to get the autocompletion in the automation editor.

**Comment by AdrianGarside** [comment]
I tried to find a list in the Bambu Studio code. I'm sure it must be there somewhere but I wasn't able to find it.

Ooh, here's an upcoming new state:
            else if (obj->print_status == "SLICING") {
                if (obj->queue_number <= 0) {
                    prepare_text = wxString::Format(_L("Cloud Slicing..."));

**Comment by AdrianGarside** [comment]
std::string print_status;      /* enum string: FINISH, SLICING, RUNNING, PAUSE, INIT, FAILED */

I don't see INIT used anywhere in the Bambu Studio code though - I think that's a stale comment and it became PREPARE

**Comment by AdrianGarside** [comment]
> RuntimeError

Is there any more log context around that error? There's clearly an issue but I don't know what list was involved.

**Comment by AdrianGarside** [comment]
https://github.com/greghesp/ha-bambulab/releases/tag/v1.4.13 has the fix for the missing ‘pause’ printer status option.

**Comment by man55** [comment]
This seems to be the same problem mentioned earlier. It is not necessary to turn off the printer; the sensors freeze and stop updating during the printing process.
Just yesterday everything was stuck at 2% printing and is no longer updated, although after that I started 4 other prints, turned the printer off and on.
v1.4.12
https://github.com/greghesp/ha-bambulab/issues/191#issuecomment-1719557963

![Screenshot 2023-09-15 095239](https://github.com/greghesp/ha-bambulab/assets/30772900/d286d707-8f7e-47ce-9167-1661cea3a04e)

**Comment by Anrolosia** [comment]
@man55 have you tested version 1.4.13 as mentioned by @AdrianGarside ? I'm on the 1.4.13 and so far so good, no problem.

**Comment by AdrianGarside** [comment]
I need debug logs to have any hope of diagnosing ongoing reproes of this:
![image](https://github.com/greghesp/ha-bambulab/assets/26147576/eeda0da2-d28b-4938-aa31-23a70cdd24c8)

**Comment by AdrianGarside** [comment]
Since the original report for this issue was understood and fixed (and was specific to the printer being turned back on), please open a new issue with debug logs if you still see a case where the sensors unexpectedly stop working.

Please make sure to be aware of #174 if you are running a P1P/S with the latest firmware to make sure you aren't hitting that problem.

**Comment by man55** [comment]
> @man55 have you tested version 1.4.13 as mentioned by @AdrianGarside ? I'm on the 1.4.13 and so far so good, no problem.

This version worked for a week and froze again. It was necessary to restart the integration. Two days later it froze again.
Bullshit.

**Comment by AdrianGarside** [comment]
Do you have debug logs? Without those I can’t help you. Please open a new issue with debug logs covering the repro.
