### ISSUE TITLE
[Bug] EXTERNAL: Error opening camera streams due to X1 firmware issues

### ISSUE THREAD

**Issue by bubbleytea** [greghesp/ha-bambulab#221]
### Describe the bug

Camera streams stopped working and I see this error in the logs:

```
2023-09-19 21:17:18.749 ERROR (stream_worker) [homeassistant.components.stream.stream.camera.x1c_****_camera] Error from stream worker: Error opening stream (ERRORTYPE_5, I/O error) rtsps://****:****@192.168.1.168/streaming/live/1
```

Camera streams time out:
![image](https://github.com/greghesp/ha-bambulab/assets/142062541/31798e23-5183-4b54-8bf4-143dca1d3de4)

They were working before when I first set up the integration.

### To Reproduce

Install integration and add devices. Eventually the streams just stop loading.

### Expected Behaviour

Camera stream loads

### What device are you using?

X1C

### Firmware Version

01.06.03.00

### Home Assistant Version

2023.9.2

### Component Version

1.5.0

### Log Extracts

2023-09-19 21:17:18.749 ERROR (stream_worker) [homeassistant.components.stream.stream.camera.x1c_***_camera] Error from stream worker: Error opening stream (ERRORTYPE_5, I/O error) rtsps://****:****@192.168.1.168/streaming/live/1

### Other Information

I don't see any other errors in the logs. Is there anything else I can do to help debug?

**Comment by SartorialGrunt0** [comment]
My camera stream has never worked for what its worth. Not certain why.

**Comment by bubbleytea** [comment]
> Has the IP of your printer changed by any chance?

No, I checked and the IPs of all the printers are still the same. All of the other sensors are working properly (I'm assuming those would be broken too, if the IP changed?).

**Comment by IIDemoniaKII** [comment]
Hello,

I have the same problem.

Error from stream worker: Error opening stream (EXIT, Immediate exit requested) rtsps://****:****@us.mqtt.bambulab.com/streaming/live/1

**Comment by IIDemoniaKII** [comment]
Thank you for your work !

**Comment by IIDemoniaKII** [comment]
Good morning,

Still does not work.

Tried to install locally, without success.

I am attaching error logs, but I am not sure that they correspond to this problem.

----------------------------------------

Logger: aiohttp.server
Source: custom_components/bambu_lab/camera.py:64
Integration: Bambu Lab ([documentation](https://github.com/greghesp/ha-bambulab), [issues](https://github.com/greghesp/ha-bambulab/issues))
First occurred: 18:10:13 (2 occurrences)
Last logged: 18:11:23

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 148, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 763, in get
    return await self.handle(request, camera)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 803, in handle
    stream = await camera.handle_async_mjpeg_stream(request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 624, in handle_async_mjpeg_stream
    return await self.handle_async_still_stream(request, self.frame_interval)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 612, in handle_async_still_stream
    return await async_get_still_stream(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 280, in async_get_still_stream
    img_bytes = await image_cb()
                ^^^^^^^^^^^^^^^^
  File "/config/custom_components/bambu_lab/camera.py", line 76, in async_camera_image
    stream_source = await self.stream_source()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bambu_lab/camera.py", line 64, in stream_source
    url = URL(self.coordinator.get_model().camera.rtsp_url).with_user('bblp').with_password(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yarl/_url.py", line 835, in with_user
    raise ValueError("user replacement is not allowed for relative URLs")
ValueError: user replacement is not allowed for relative URLs

**Comment by IIDemoniaKII** [comment]
Hello, I can't find the version on HACS.

**Comment by IIDemoniaKII** [comment]
Yes, i see v1.7.1-dev1

**Comment by IIDemoniaKII** [comment]
I will try to uninstall completely and download again

**Comment by IIDemoniaKII** [comment]
No, it doesn't appear
![1](https://github.com/greghesp/ha-bambulab/assets/82895550/0a719b59-d299-41cf-aeba-1f8f3421cf88)
![2](https://github.com/greghesp/ha-bambulab/assets/82895550/f8cbeb0c-59b6-4e96-88ce-ee34194af48e)

**Comment by IIDemoniaKII** [comment]
![Capture d'écran 2023-09-30 210234](https://github.com/greghesp/ha-bambulab/assets/82895550/b639da23-396c-4206-ae48-c1df88099826)

**Comment by IIDemoniaKII** [comment]
Upload the file directly to home assistant, unfortunately it still doesn't work

Logger: homeassistant.components.stream.stream.camera.x1c_00m09a371200619_camera
Source: components/stream/__init__.py:434
Integration: Stream ([documentation](https://www.home-assistant.io/integrations/stream), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+stream%22))
First occurred: 21:30:52 (7 occurrences)
Last logged: 21:34:22

Error from stream worker: Error opening stream (PROTOCOL_NOT_FOUND, Protocol not found) ://bblp:edc1d6f5@disable

**Comment by IIDemoniaKII** [comment]
Now i see, i test

![Capture d'écran 2023-09-30 213642](https://github.com/greghesp/ha-bambulab/assets/82895550/6f3be1a3-eb60-4059-86ea-ff78337032f7)

**Comment by IIDemoniaKII** [comment]
My fault, I forgot to reactivate live. It works, thank you very much!
Beautiful evening

**Comment by IIDemoniaKII** [comment]
Hello,

New problem it seems, my timelaps is activate

Error from stream worker: Error opening stream (INVALIDDATA, Invalid data found when processing input) rtsps://****:****@192.168.68.140/streaming/live/1

**Comment by IIDemoniaKII** [comment]
Reactivate..., this printer likes to play jokes on me...

Logger: homeassistant.components.stream.stream.camera.x1c_00m09a371200619_camera
Source: components/stream/__init__.py:434
Integration: Stream ([documentation](https://www.home-assistant.io/integrations/stream), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+stream%22))
First occurred: 12:46:29 (1 occurrences)
Last logged: 12:46:29

Error from stream worker: Error opening stream (ERRORTYPE_5, I/O error) rtsps://****:****@192.168.68.140/streaming/live/1

**Comment by AdrianGarside** [comment]
Re-added IP fix up workaround: #299

**Comment by mateuszdrab** [comment]
> Re-added IP fix up workaround: #299

I've applied the fix to my copy of the component but it's still showing me the same error as @IIDemoniaKII has:

`Error from stream worker: Error opening stream (ERRORTYPE_5, I/O error) rtsps://****:****@192.168.0.136/streaming/live/1`

**Comment by mateuszdrab** [comment]
Lan View is enabled - I was just playing with the local instance of Bambu Studio and figured out I can get a cloud stream on demand by running bambu_source and piping it into ffmpeg which is what the studio does. bambu_source takes a token from a file called url.txt which I presume is populated from some API call the studio does.

Printer is in cloud mode - integration is connected using cloud mode as well

**Comment by mateuszdrab** [comment]
> > Lan View is enabled - I was just playing with the local instance of Bambu Studio and figured out I can get a cloud stream on demand by running bambu_source and piping it into ffmpeg which is what the studio does. bambu_source takes a token from a file called url.txt which I presume is populated from some API call the studio does.
> > 
> > Printer is in cloud mode - integration is connected using cloud mode as well
> 
> Can I get more details on the steps to view the cloud stream?

I just figured out what happens behind the scenes when you Go Live from Bambu Studio. If you enable that switch there, you can access the camera via ftp://localhost:1234 which is the result of Bambu Source bring executed and piping the output into ffmpeg which is then made to listen on port 1234.
However, the token in the url.txt file which is needed to start bambu source isn't valid forever so I'd need to figure out how that token is generated before the above steps make sense.

**Comment by mateuszdrab** [comment]
> > > > Lan View is enabled - I was just playing with the local instance of Bambu Studio and figured out I can get a cloud stream on demand by running bambu_source and piping it into ffmpeg which is what the studio does. bambu_source takes a token from a file called url.txt which I presume is populated from some API call the studio does.
> > > > Printer is in cloud mode - integration is connected using cloud mode as well
> > > 
> > > 
> > > Can I get more details on the steps to view the cloud stream?
> > 
> > I just figured out what happens behind the scenes when you Go Live from Bambu Studio. If you enable that switch there, you can access the camera via ftp://localhost:1234 which is the result of Bambu Source bring executed and piping the output into ffmpeg which is then made to listen on port 1234. However, the token in the url.txt file which is needed to start bambu source isn't valid forever so I'd need to figure out how that token is generated before the above steps make sense.
> 
> That's purely for their "go live" functionality that allows you to stream to Twitch or whatever.  All that does is take the proprietary stream, and then re-broadcasts it on a local IP address from your machine.
> 
> > Regarding the camera, does anyone with X1C actually got it working? If so, I'll just go and check things with Bambu support.
> 
> Sometimes.  I've already raised it with them and they are aware and have found the  bug

Awesome, I hope the fix makes it into the new upcoming firmware.

**Comment by brantje** [comment]
I get the same error, but my URL looks very different:
```
Error from stream worker: Error opening stream (PROTOCOL_NOT_FOUND, Protocol not found) ://bblp:4xxfxxe@disable
```
I suppose re-adding the integration will solve this?

**Comment by AdrianGarside** [comment]
> I get the same error, but my URL looks very different:
> 
> ```
> Error from stream worker: Error opening stream (PROTOCOL_NOT_FOUND, Protocol not found) ://bblp:4xxfxxe@disable
> ```
> 
> I suppose re-adding the integration will solve this?

@disable means you don't have lan view enabled.

**Comment by AdrianGarside** [comment]
Fix to make Camera entity disabled when lan view is not enabled:
#325

**Comment by AdrianGarside** [comment]
I'm going to mark this as won't fix for now as there are no known issues in the integration handling of the rtsp feed - all indications are that the remaining problems are all bugs in the firmware implementation on the Bambu side.

**Comment by mateuszdrab** [comment]
Are there any updates on the support case with Bambu Lab?

Lastest firmware came in recently and the issue still exists.

**Comment by anoblet** [comment]
I can get a camera stream after first boot on an X1C using HA. After that it drops off. I'm not sure when, or why, though diffing the i/o could provide a clue. Does the FW just drop multiple streams?

**Comment by AdrianGarside** [comment]
The RTSP support in the firmware is just very buggy unfortunately.

**Comment by anoblet** [comment]
It hasn't bothered me much, it seems like a finicky problem to solve. Everything else works great :)

**Comment by jmwaldrip** [comment]
I was having the same right after I upgraded to firmware 1.7.01.00. I played with it for a while, but after I hard rebooted the printer it started working. 

I am having some timestamp differences errors but it seems to be working well. 

![image](https://github.com/greghesp/ha-bambulab/assets/1836329/74744226-113f-4730-8fc2-1fef50d337f7)

I will add another comment if it stops working or has any issues. So far seems pretty stable. 

I am also starting to play with WebRTC and streaming it through that to see if it makes a difference.

**Comment by AdrianGarside** [comment]
What I’m finding is that with webrtc and pointing both my production and test instance of home assistant at the same go2rtc instance then I have a reliable connection. But if I restart home assistant (and with my docker based setup that restarts go2rtc) then the connection is broken until I restart the printer.

**Comment by AdrianGarside** [comment]
While when I had two separate go2rtc instances the connection I think was not reliable even if I didn’t restart my production home assistant instance but I’m not certain.

**Comment by jmwaldrip** [comment]
Oh interesting, I haven't had time to try the a webrtc server yet. What are you using for the docker container? I was thinking of throwing it on my k8s cluster.

**Comment by jneilliii** [comment]
go2rtc is one I've used outside of HA before, but think it's actually bundled in HA too IIRC

**Comment by jmwaldrip** [comment]
Yeah, its bundled in HA. But I have HA running in my K8s cluster. I was going to put it on its own deployment etc so I didn't have to deal with the ingress complexity.

**Comment by AdrianGarside** [comment]
It's part of the included webrtc integration I think - not sure if there's other copies of go2rtc but each of my HA instances starts it's own copy of go2rtc as part of the webrtc integration. Initially I had both my production and test instances webrtc pointing at their own go2rtc so each of those was separately connecting to the printer. And that seems to be the source of some of the reliability issues I was seeing. Only having one instance pointed at the printer seems to have made things much more reliable - as long as that instance never disconnects and reconnects.

**Comment by anoblet** [comment]
Is there a guide on how to setup WebRTC/go2rtc for this integration?

**Comment by AdrianGarside** [comment]
https://github.com/greghesp/ha-bambulab/discussions/453#discussioncomment-8267217

**Comment by mateuszdrab** [comment]
This is so annoying, is Bambu doing anything about this? 
I was hoping last firmware release would fix it but it's still barely ever working.

**Comment by lukbe** [comment]
Hello, I have with my X1C and Home Assistant integration same problem = in the log is error Error from stream worker: Error opening stream. 
Integration version 2.0.21
Home assistant 2024.6.4

Exist a solution?

**Comment by miketarg** [comment]
Logger: homeassistant.components.stream.stream.camera.bambu_lab_x1c_camera
Source: components/stream/__init__.py:448
integration: Stream (documentation, issues)
First occurred: 10:27:08 PM (4 occurrences)
Last logged: 10:33:28 PM

Error from stream worker: Error opening stream (ERRORTYPE_5, I/O error, rtsps://****:****@192.168.0.228:322/streaming/live/1)


I have this issue, is this being looked at by anyone I would really appreciate a response.

**Comment by undert03** [comment]
Having same issue. Get a VLC stream error as well when i use the RTSPS url.

Log attached

[home-assistant_bambu_lab_2024-11-08T16-29-25.016Z.log](https://github.com/user-attachments/files/17681488/home-assistant_bambu_lab_2024-11-08T16-29-25.016Z.log)

**Comment by AdrianGarside** [comment]
Restarting your printer will help briefly. There is nothing this integration can do to make the video feed work reliably due to bugs in the printer implementation that have gone unfixed.

**Comment by undert03** [comment]
Thanks for the response. What specifically is the issue on the firmware side. Do you have any references to it?

**Comment by AdrianGarside** [comment]
If the issue was specifically understood Bambu would probably have fixed it by now. There’s a link above to the Bambu studio GitHub.

**Comment by otelconsulting** [comment]
Ok so I don't know if its been discovered before but I am just going to throw it out here. 

Since before and after posting my comment 5 days ago I have been really trying to get this working all the way to docker containers and elaborate command line. Nothing seemed to work even on reboot of the X1 I could not get the stream to ever show.

So i stumble onto this post and figure why not, I hope its that easy.
[https://www.wolfwithsword.com/bambulabs-x1c-camera-in-home-assistant/](https://www.wolfwithsword.com/bambulabs-x1c-camera-in-home-assistant/)

Upon configuring I get the Home Assistant error message _"The stream integration is not set up. Please ensure that you have 'default_config:' or 'stream:' in your configuration.yaml". First google result brought me here.
[https://github.com/home-assistant/core/issues/64675](https://github.com/home-assistant/core/issues/64675)

With my configuration I just added stream: to me HA configuration.yaml and restarted. After reboot my camera on my X1 has been working as expected. The logs no long output the stream error. I have had my printer up for about 3 days now without a reboot and camera images are still working. I did notice it might take 2-5 seconds for the image to start streaming and there is some skipping in the frame rate but i will take it!

I have also removed the stream: in my configuration to see if it would go back to giving me the error and sure enough it went back to the camera not working.

**Comment by undert03** [comment]
Ok so I don't know if its been discovered before but I am just going to throw it out here. 

Since before and after posting my comment 5 days ago I have been really trying to get this working all the way to docker containers and elaborate command line. Nothing seemed to work even on reboot of the X1 I could not get the stream to ever show.

So i stumble onto this post and figure why not, I hope its that easy.
[https://www.wolfwithsword.com/bambulabs-x1c-camera-in-home-assistant/](https://www.wolfwithsword.com/bambulabs-x1c-camera-in-home-assistant/)

Upon configuring I get the Home Assistant error message _"The stream integration is not set up. Please ensure that you have 'default_config:' or 'stream:' in your configuration.yaml". First google result brought me here.
[https://github.com/home-assistant/core/issues/64675](https://github.com/home-assistant/core/issues/64675)

With my configuration I just added stream: to me HA configuration.yaml and restarted. After reboot my camera on my X1 has been working as expected. The logs no long output the stream error. I have had my printer up for about 3 days now without a reboot and camera images are still working. I did notice it might take 2-5 seconds for the image to start streaming and there is some skipping in the frame rate but i will take it!

I have also removed the stream: in my configuration to see if it would go back to giving me the error and sure enough it went back to the camera not working.

**Comment by logikal** [comment]
Possibly related issue with `stream` integration inside HASS/dependent components:
https://github.com/home-assistant/core/issues/132678

**Comment by AdrianGarside** [comment]
That definitely sounds like it would break the X1 camera.

**Comment by DaKo85** [comment]
Hi everybody,

i have the the same problem with my X1C. 
Error requesting stream: camera.x1c_SN_kamera does not support play stream service
