### ISSUE TITLE
[Bug] Chamber image on P1S doesn't work reliably on printer restart

### ISSUE THREAD

**Issue by AdrianGarside** [greghesp/ha-bambulab#362]
### Describe the bug

Looks like the initial connection attempt failed and we don't have any retry / reconnection logic to handle this.

### To Reproduce

.

### Expected Behaviour

.

### What device are you using?

X1C

### Diagnostic Output

```shell
2023-12-25 23:48:19.159 DEBUG (Thread-6 (mqtt_listen_thread)) [custom_components.bambu_lab.pybambu] Starting Image Camera thread
2023-12-25 23:48:19.160 DEBUG (Thread-12) [custom_components.bambu_lab.pybambu] Image Camera thread started.
2023-12-25 23:48:19.224 DEBUG (Thread-6 (mqtt_listen_thread)) [custom_components.bambu_lab.pybambu] Received data from: P1S
2023-12-25 23:48:19.225 DEBUG (Thread-6 (mqtt_listen_thread)) [custom_components.bambu_lab] Manually updated bambu_lab data
2023-12-25 23:48:19.227 DEBUG (Thread-6 (mqtt_listen_thread)) [custom_components.bambu_lab] Manually updated bambu_lab data
2023-12-25 23:48:19.233 DEBUG (Thread-6 (mqtt_listen_thread)) [custom_components.bambu_lab.pybambu] Received data from: P1S
2023-12-25 23:48:19.233 DEBUG (Thread-6 (mqtt_listen_thread)) [custom_components.bambu_lab.pybambu] Got Version Data
2023-12-25 23:48:19.234 DEBUG (Thread-6 (mqtt_listen_thread)) [custom_components.bambu_lab.pybambu] Device is P1S
2023-12-25 23:48:19.235 DEBUG (Thread-6 (mqtt_listen_thread)) [custom_components.bambu_lab.pybambu] Received data from: P1S
2023-12-25 23:48:19.235 DEBUG (Thread-6 (mqtt_listen_thread)) [custom_components.bambu_lab.pybambu] Got Version Data
2023-12-25 23:48:19.235 DEBUG (Thread-6 (mqtt_listen_thread)) [custom_components.bambu_lab.pybambu] Device is P1S
2023-12-25 23:48:19.180 ERROR (Thread-12) [root] Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/config/custom_components/bambu_lab/pybambu/bambu_client.py", line 102, in run
    sslSock = ctx.wrap_socket(sock, server_hostname=hostname)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/ssl.py", line 1108, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.11/ssl.py", line 1379, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer
```

**Comment by Metallica22** [comment]
Hello,

I'm experiencing the same issue with the P1P. I always completely turn it off using a WiFi socket when it's not in use. When I send a new print job to the printer, all the information in the integration gets updated, except for the camera stream. However, when I reconfigure the device in the settings under 'Devices' - 'Bambu Lab', the camera stream starts working again. If you need more information, please feel free to ask. 

Best regards, Patrick B.

**Comment by AdrianGarside** [comment]
@Metallica22 I haven't been able to reproduce to test this fix, but could you please give this version a go and see if it fixes things for you? If not, please grab debug logs of the failure:
https://github.com/greghesp/ha-bambulab/releases/tag/v2.0.3-dev11

**Comment by Metallica22** [comment]
@AdrianGarside Thank you for your quick reply. I have installed the new version, but I won’t be able to test it until about 27 hours from now, as my current print is still running for that long. I will test it and report back to you.

**Comment by Metallica22** [comment]
Unfortunately, the beta release did not solve the problem.  
I now strongly suspect my crappy Fritzbox is causing this problem.

**Comment by AdrianGarside** [comment]
What do the debug logs show?
