### ISSUE TITLE
Stops working after a while

### ISSUE THREAD

**Issue by Ali229** [greghesp/ha-bambulab#5]
I know this is still a WIP but I wanted to make sure this issue was covered, after a little while the integration stops working and shows this in log:

```
Logger: homeassistant.config_entries
Source: helpers/entity_component.py:181
First occurred: 10:34:54 AM (2 occurrences)
Last logged: 10:34:54 AM

Error unloading entry Bambu for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 533, in async_unload
    result = await component.async_unload_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 131, in async_unload_entry
    return await component.async_unload_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 181, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
```

**Comment by Ali229** [comment]
Might also be useful
```
Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 182, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 330, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 135, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 390, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 566, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 607, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 572, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 466, in state
    value = self.native_value
  File "/config/custom_components/bambu_lab/sensor.py", line 62, in native_value
    return self.entity_description.value_fn(self.coordinator.data)
  File "/config/custom_components/bambu_lab/definitions.py", line 65, in <lambda>
    value_fn=lambda device: device.info.wifi_signal
AttributeError: 'NoneType' object has no attribute 'info'
```

**Comment by AdrianGarside** [comment]
@Ali229 Do you still see this with the changes that just went in today?

**Comment by AdrianGarside** [comment]
I do recall fixing an exception in that call stack but I can't remember what the error was. I'm going to mark this as completed since I've had zero downtime with my fixes that are now in. Please reopen if you still see issues with the latest version.

**Comment by AdrianGarside** [comment]
Or not - I don't have permissions to close issues I didn't open. @greghesp can that be fixed?

**Comment by AdrianGarside** [comment]
> Let me have a look. PS: Do you have Discord?
Yes I do.

**Comment by AdrianGarside** [comment]
I'm already on there - 'Arathranar#1275'

**Comment by Ali229** [comment]
Sorry about not following up, I've since stopped using this repo and started using the config with nodered, when that stops working I'll be back :D, I'm guessing this pulls the same data as the method by @WolfwithSword.

**Comment by WolfwithSword** [comment]
> Sorry about not following up, I've since stopped using this repo and started using the config with nodered, when that stops working I'll be back :D, I'm guessing this pulls the same data as the method by @WolfwithSword.

We're working on making this up to par with the nodered flow, if not better :)
