### ISSUE TITLE
Unknown error occurred

### ISSUE THREAD

**Issue by nappyjim** [greghesp/ha-bambulab#51]
Trying to setup the integration, I input the IP, access code, and serial number.  I get an unknown error occurred everytime.  I restarted printer. Restarted HA.  Created new access doe. Confirmed ping to printer.  Confirmed serial number has been typed in correct.
![unknown error](https://user-images.githubusercontent.com/71914301/226125088-91400d73-554e-4056-a477-d8abdc50fedd.png)

**Comment by dz0ny** [comment]
```py
File "/config/custom_components/bambu_lab/config_flow.py", line 31, in async_step_user
success = await bambu.try_connection()
File "/config/custom_components/bambu_lab/pybambu/bambu_client.py", line 188, in try_connection
self.client.connect(self.host, self._port)
File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 914, in connect
return self.reconnect()
File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1044, in reconnect
sock = self._create_socket_connection()
File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
File "/usr/local/lib/python3.10/socket.py", line 845, in create_connection
raise err
File "/usr/local/lib/python3.10/socket.py", line 833, in create_connection
sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
```

**Comment by nappyjim** [comment]
@dz0ny , I'm confused by your reply.  Are you asking for my logs?  Which log would that be?

**Comment by nappyjim** [comment]
Think I found the log...

`This error originated from a custom integration.

Logger: aiohttp.server
Source: custom_components/bambu_lab/pybambu/bambu_client.py:188
Integration: bambu_lab (documentation, issues)
First occurred: March 18, 2023 at 12:53:10 PM (3 occurrences)
Last logged: 9:08:31 AM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 67, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 235, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 146, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 180, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 271, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/bambu_lab/config_flow.py", line 31, in async_step_user
    success = await bambu.try_connection()
  File "/config/custom_components/bambu_lab/pybambu/bambu_client.py", line 188, in try_connection
    self.client.connect(self.host, self._port)
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 914, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1044, in reconnect
    sock = self._create_socket_connection()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
    return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
  File "/usr/local/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/local/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
`
