### ISSUE TITLE
[Bug] Broken after 2.0.18 

### ISSUE THREAD

**Issue by 00svd00** [greghesp/ha-bambulab#511]
### Describe the bug

After 2.0.18 update integration is not working for me

### To Reproduce

Printer Basmbulab X1C
After update integration is not working

### Expected Behaviour

Integration is working properly

### What device are you using?

X1C

### Diagnostic Output

```shell
Unexpected exception importing platform custom_components.bambu_lab.config_flow
    Unexpected exception importing platform custom_components.bambu_lab.application_credentials

Traceback (most recent call last):
  File "/opt/homeassistant/lib/python3.11/site-packages/homeassistant/loader.py", line 1025, in _load_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homeassistant/lib/python3.11/site-packages/homeassistant/loader.py", line 1058, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1128, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/homeassistant/.homeassistant/custom_components/bambu_lab/__init__.py", line 6, in <module>
    from .coordinator import BambuDataUpdateCoordinator
  File "/home/homeassistant/.homeassistant/custom_components/bambu_lab/coordinator.py", line 142
    LOGGER.debug(f"{self.config_entry.data["device_type"]} HA POLL: MQTT connected: {self.client.connected}")
                                            ^^^^^^^^^^^
SyntaxError: f-string: unmatched '['
```

**Comment by AdrianGarside** [comment]
This should fix that error. Please can you confirm:
https://github.com/greghesp/ha-bambulab/releases/tag/v2.0.19

**Comment by 00svd00** [comment]
Seems that everything is OK now. Thank you!
