### ISSUE TITLE
Help understanding why all is unavailable

### ISSUE THREAD

**Issue by carltonwb** [greghesp/ha-bambulab#56]
### Describe the bug

I installed the HACS integration, entered my details and the integration was created.
When I open the integration all the Sensor are unavailable. It gives me the following message.
**This entity is no longer being provided by the bambu_lab integration. If the entity is no longer in use, delete it in settings.**

What should I check. I did restart the printer and it is in LAN only mode.

### To Reproduce

Don't know

### Expected Behaviour

To show sensors

### What device are you using?

P1P

### Firmware Version

01.02.02.00

### Home Assistant Version

2023.3.5

### Component Version

3c054df

### Log Extracts

This error originated from a custom integration.

Logger: aiohttp.server
Source: custom_components/bambu_lab/pybambu/bambu_client.py:188
Integration: Bambu Lab (documentation, issues)
First occurred: 6:55:12 AM (1 occurrences)
Last logged: 6:55:12 AM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 67, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 94, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 235, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 146, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 180, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 271, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/bambu_lab/config_flow.py", line 31, in async_step_user
    success = await bambu.try_connection()
  File "/config/custom_components/bambu_lab/pybambu/bambu_client.py", line 188, in try_connection
    self.client.connect(self.host, self._port)
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 914, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1044, in reconnect
    sock = self._create_socket_connection()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
    return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
  File "/usr/local/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/local/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

**Comment by npike** [comment]
From home assistant, can you ping the IP for your P1P?

**Comment by LayerCakeMakes** [comment]
Did you rename the integration or the device after adding it? For me that seems to break things.

**Comment by carltonwb** [comment]
I have 3 P1P's and 1 X1C, I can ping them all.
Yes I did rename them.
I will delete them and try again without renaming.

**Comment by LayerCakeMakes** [comment]
> If this is the cause, could you open a new bug report please? Just to keep it clear what the issue is

I've tested this on my end and renaming the device seems to work fine but renaming the integration breaks it. I've created #57 for this.
