### ISSUE TITLE
[Bug] Uncaught thread exception takes out the mqtt listener thread

### ISSUE THREAD

**Issue by AdrianGarside** [greghesp/ha-bambulab#7]
2023-02-09 00:46:03.841 DEBUG (Thread-2 (_thread_main)) [custom_components.bambu_lab.pybambu] On Message: Received Message: b'{"print":{"wifi_signal":"-67dBm","command":"push_status","msg":1,"sequence_id":"29036"}}'
2023-02-09 00:46:05.854 ERROR (Thread-2 (_thread_main)) [root] Uncaught thread exception

From that point onwards the main thread believes it's connnected but no more payload is received until you restart home assistant.

**Comment by AdrianGarside** [comment]
I attempted to fix this in my open PR and I thought it was helping but it looks like the fix I made isn't sufficient. First line is from catching the exception but trying to log data about it _seems_ to still trigger the thread exception:

2023-02-09 16:57:46.071 DEBUG (Thread-4 (_thread_main)) [custom_components.bambu_lab.pybambu] An exception of type JSONDecodeError occurred. Arguments:
2023-02-09 16:57:46.073 ERROR (Thread-4 (_thread_main)) [root] Uncaught thread exception

**Comment by AdrianGarside** [comment]
Tweaked the way I process/log the exception to see if that helps.

**Comment by AdrianGarside** [comment]
It may also be (possibly likely even) that the incomplete payload is just a symptom that the mqtt lib has fallen over and my handling of the json exception makes no difference because once we return it's dead. I can _potentially_ set the connection as disconnected and try to trigger reconnect but if the mqtt lib got into a bad state, it might not let me recover it.

**Comment by AdrianGarside** [comment]
The latest tweak to the try/catch I added in the just completed PR appears to have resolved this. The exception is now caught and logged but the mqtt listener thread no longer dies:

2023-02-10 05:44:13.943 DEBUG (Thread-2 (_thread_main)) [custom_components.bambu_lab.pybambu] On Message: Received Message: b'{"mc_print":{"param":"[AMS][TASK]ams0 en=1,mode=0'
2023-02-10 05:44:13.943 DEBUG (Thread-2 (_thread_main)) [custom_components.bambu_lab.pybambu] An exception occurred:
2023-02-10 05:44:13.944 DEBUG (Thread-2 (_thread_main)) [custom_components.bambu_lab.pybambu] Type: <class 'json.decoder.JSONDecodeError'>
2023-02-10 05:44:13.944 DEBUG (Thread-2 (_thread_main)) [custom_components.bambu_lab.pybambu] Args: ('Unterminated string starting at: line 1 column 22 (char 21)',)

**Comment by AdrianGarside** [comment]
Closing issue as fixed.

**Comment by AdrianGarside** [comment]
Nope, hit another of those cases and this time the uncaught exception error occured and the connection silently died again:

2023-02-10 10:06:02.598 DEBUG (Thread-5 (_thread_main)) [custom_components.bambu_lab.pybambu] On Message: Received Message: b'{"mc_print":{"param":"[SYS] Dev[suart0]fw_cnt6 tx'
2023-02-10 10:06:02.598 DEBUG (Thread-5 (_thread_main)) [custom_components.bambu_lab.pybambu] An exception occurred:
2023-02-10 10:06:02.599 DEBUG (Thread-5 (_thread_main)) [custom_components.bambu_lab.pybambu] Type: <class 'json.decoder.JSONDecodeError'>
2023-02-10 10:06:02.599 DEBUG (Thread-5 (_thread_main)) [custom_components.bambu_lab.pybambu] Args: ('Unterminated string starting at: line 1 column 22 (char 21)',)
2023-02-10 10:06:02.600 ERROR (Thread-5 (_thread_main)) [root] Uncaught thread exception

So the problem does seem to be internal the mqtt lib and I'll see if I can mitigate by reinitializing the connection if a json decode error occurs since that's likely going to take it down ~50% of the time.

**Comment by AdrianGarside** [comment]
Do you see that symptom when you run with your X1?

Latest repro had valid payload, did not throw an json decode exception, and the thread still crashed:
2023-02-10 17:05:31.319 DEBUG (Thread-5 (_thread_main)) [custom_components.bambu_lab.pybambu] On Message: Received Message: b'{"mc_print":{"param":"[AMS][Period]:len=0.000m;buf=-0.17;hall_e=1214mV,cut=1553mV","command":"push_info","sequence_id":"201056"}}'
2023-02-10 17:05:31.370 ERROR (Thread-5 (_thread_main)) [root] Uncaught thread exception

Where an earlier case of bad data was handled without issues:
2023-02-10 14:51:21.912 DEBUG (Thread-4 (_thread_main)) [custom_components.bambu_lab.pybambu] On Message: Received Message: b'{"mc_print":{"param":"[AMS][TASK]ams0 en=1,mode=0'
2023-02-10 14:51:21.912 DEBUG (Thread-4 (_thread_main)) [custom_components.bambu_lab.pybambu] An exception occurred:
2023-02-10 14:51:21.913 DEBUG (Thread-4 (_thread_main)) [custom_components.bambu_lab.pybambu] Type: <class 'json.decoder.JSONDecodeError'>
2023-02-10 14:51:21.913 DEBUG (Thread-4 (_thread_main)) [custom_components.bambu_lab.pybambu] Args: ('Unterminated string starting at: line 1 column 22 (char 21)',)

**Comment by AdrianGarside** [comment]
No pattern that I can discern. Sometimes it hits in 1-2 hours., maybe even under an hour once. Other times it’s still fine overnight. Planning to see if it’s possible  to

**Comment by AdrianGarside** [comment]
I found this for the uncaught thread exception. It is inside the mqtt lib as I suspected:

Logger: root
Source: /usr/src/homeassistant/homeassistant/bootstrap.py:342
First occurred: February 10, 2023 at 9:52:06 PM (1 occurrences)
Last logged: February 10, 2023 at 9:52:06 PM

Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3591, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1756, in loop_forever
    rc = self._loop(timeout)
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1164, in _loop
    rc = self.loop_read()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1556, in loop_read
    rc = self._packet_read()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 2439, in _packet_read
    rc = self._packet_handle()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3033, in _packet_handle
    return self._handle_publish()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3283, in _handle_publish
    (topic, packet) = struct.unpack(pack_format, packet)
struct.error: bad char in struct format

**Comment by AdrianGarside** [comment]
The exception is definitely happening inside the mqtt lib so the est we can do, modulo a fix in the mqtt lib itself, is to attempt to reinitialize the connection if we can detect this state. A watchdog time for last received message ought to be viable to detect it. I haven't seen anything better in the mqtt lib api. And I don't yet know if you can successfull reinitialize the connection when it's gotten itself messed up this way.

2023-02-11 17:58:27.573 DEBUG (Thread-8 (_thread_main)) [custom_components.bambu_lab.pybambu] Received PUBLISH (d0, q0, r0, m0), 'device/01S00A292501557/report', ...  (90 bytes)
2023-02-11 17:58:27.573 DEBUG (Thread-8 (_thread_main)) [custom_components.bambu_lab.pybambu] On Message: Received Message:
2023-02-11 17:58:27.574 DEBUG (Thread-8 (_thread_main)) [custom_components.bambu_lab.pybambu] b'{"mc_print":{"param":"[BMC] M622: need skip","command":"push_info","sequence_id":"11862"}}'
2023-02-11 17:58:27.576 ERROR (Thread-8 (_thread_main)) [root] Uncaught thread exception
2023-02-11 17:58:36.001 DEBUG (MainThread) [custom_components.bambu_lab.pybambu] Connected: True
2023-02-11 17:58:36.002 DEBUG (MainThread) [custom_components.bambu_lab] Coordinator update connected? True
2023-02-11 17:58:36.002 DEBUG (MainThread) [custom_components.bambu_lab.pybambu] Connected: True

@greghesp there's a comment that you can't call back into home assistant from the mqtt message handler. My guess is that's because the call is on the wrong thread. An option, and I have no idea if it's viable, is to do all the processing of the mqtt messages on the main thread. We can then wrap the entire processing in try/except and I expect it can then call back directly into home assistant to update the sensors in real time (vs the 10 second poll we currently have). Thoughts? We'd have to find some way to get run regularly (~once a second) on the main thread to be able to process the queued messages. And the processing will probably need to not take up too much wallclock time. 

Another alternative (no idea if/how you can do it in python/home-assistant) is to spin up a separate thread to do a blocking loop. Probably doesn't solve the callback for live sensor updates but it would still let us catch the mqtt exception and immediately attempt the recovery.

**Comment by AdrianGarside** [comment]
Ok, I have the custom background thread going to see if that recovers from these exceptions automatically or not. Should know by tomorrow morning :)

**Comment by AdrianGarside** [comment]
I may be misunderstanding it but from observation home assistant only updates the displayed values every ten seconds which matches the SCAN_INTERVAL value for the _async_update_self calls in coordinater.py. So while our knowledge of the sensors is updated in real time via the MQTT, HA's view of them isn't.

Yes, that's what I'm testing now. The first attempt just tried to keep the current mqtt instance going by restarting the loop immediately after it throws the exception but it just immediately threw the same exception again. So now I'm setting the connection to disconnected and letting the background thread exit with the hope that the 10s pool will be able to successfully reconnect with a new instance of the mqtt client. I can't see why that approach wouldn't work but I haven't hit the exception again yet to confirm it works.

**Comment by AdrianGarside** [comment]
What I see if I turn, for example, one of the fans on or off is that I see the mqtt payload arrive and get processed almost immediately. But HA only updates it's view of the sensor values when the 10s poll fires and it retrieves the device again.

Ah, just saw you're edit :). Yes - that's what I was referring to above with the idea of doing the mqtt processing on the main thread since I _think_ that would then let you make the callback successfully. But I'm fairly sure there'd be some significant downsides/new issues caused by trying to do that. For now I've just set up my own thread so I can wrap the mqtt lib with a try/except and flag the connection as dead if it throws an except so the 10s polling ought to reconnect from scratch. However I didn't hit the repro overnight so I haven't yet got confirmation that mitigates the problem.

**Comment by AdrianGarside** [comment]
So I re-enabled that callback to see what happened and it's just working for me... What was the problem you were seeing?

**Comment by AdrianGarside** [comment]
Ok, auto re-connect on mqtt lib exception is a go:
```
2023-02-12 16:21:07.698 DEBUG (Thread-3 (listen_thread)) [custom_components.bambu_lab.pybambu] Received PUBLISH (d0, q0, r0, m0), 'device/01S00A292501557/report', ...  (145 bytes)
2023-02-12 16:21:07.699 DEBUG (Thread-3 (listen_thread)) [custom_components.bambu_lab.pybambu] b'{"mc_print":{"param":"[AMS][Period]:(AMS0-S1)cmd_en=1;act_en=1;sta=4;sw=1-3-1-1;c_len=10.147m,cnt=2","command":"push_info","sequence_id":"9292"}}'
2023-02-12 16:21:07.699 DEBUG (Thread-3 (listen_thread)) [custom_components.bambu_lab] Manually updated bambu_lab data
2023-02-12 16:21:07.702 DEBUG (Thread-3 (listen_thread)) [custom_components.bambu_lab.pybambu] Sending PINGREQ
2023-02-12 16:21:07.722 DEBUG (Thread-3 (listen_thread)) [custom_components.bambu_lab.pybambu] Received PUBLISH (d0, q0, r0, m0), 'device/01S00A292501557/report', ...  (49 bytes)
2023-02-12 16:21:07.723 DEBUG (Thread-3 (listen_thread)) [custom_components.bambu_lab.pybambu] b'{"mc_print":{"param":"[AMS][Period]:bldc_i=0.00,u'
2023-02-12 16:21:07.723 DEBUG (Thread-3 (listen_thread)) [custom_components.bambu_lab.pybambu] An exception occurred:
2023-02-12 16:21:07.724 DEBUG (Thread-3 (listen_thread)) [custom_components.bambu_lab.pybambu] Type: <class 'json.decoder.JSONDecodeError'>
2023-02-12 16:21:07.724 DEBUG (Thread-3 (listen_thread)) [custom_components.bambu_lab.pybambu] Args: ('Unterminated string starting at: line 1 column 22 (char 21)',)
2023-02-12 16:21:07.724 DEBUG (Thread-3 (listen_thread)) [custom_components.bambu_lab] Manually updated bambu_lab data
2023-02-12 16:21:07.730 DEBUG (Thread-3 (listen_thread)) [custom_components.bambu_lab.pybambu] A loop exception occurred:
2023-02-12 16:21:07.730 DEBUG (Thread-3 (listen_thread)) [custom_components.bambu_lab.pybambu] Type: <class 'struct.error'>
2023-02-12 16:21:07.730 DEBUG (Thread-3 (listen_thread)) [custom_components.bambu_lab.pybambu] Args: ('bad char in struct format',)
2023-02-12 16:21:07.731 DEBUG (Thread-3 (listen_thread)) [custom_components.bambu_lab.pybambu] Disconnect: Client Disconnecting
2023-02-12 16:21:07.731 DEBUG (Thread-3 (listen_thread)) [custom_components.bambu_lab.pybambu] Sending DISCONNECT
2023-02-12 16:21:07.733 DEBUG (Thread-3 (listen_thread)) [custom_components.bambu_lab.pybambu] On Disconnect: Disconnected from Broker: 0
2023-02-12 16:21:07.734 DEBUG (Thread-3 (listen_thread)) [custom_components.bambu_lab.pybambu] Connect: Attempting Connection to 10.10.10.81
2023-02-12 16:21:07.749 DEBUG (Thread-3 (listen_thread)) [custom_components.bambu_lab.pybambu] Sending CONNECT (u0, p0, wr0, wq0, wf0, c1, k5) client_id=4LvsBZNyshx92lNvoMBOXX
2023-02-12 16:21:07.749 DEBUG (Thread-3 (listen_thread)) [custom_components.bambu_lab.pybambu] Starting listen loop
2023-02-12 16:21:07.763 DEBUG (Thread-3 (listen_thread)) [custom_components.bambu_lab.pybambu] Received CONNACK (0, 0)
2023-02-12 16:21:07.763 DEBUG (Thread-3 (listen_thread)) [custom_components.bambu_lab.pybambu] On Connect: Connected to Broker
2023-02-12 16:21:07.764 DEBUG (Thread-3 (listen_thread)) [custom_components.bambu_lab.pybambu] Now Subscribing...
2023-02-12 16:21:07.764 DEBUG (Thread-3 (listen_thread)) [custom_components.bambu_lab.pybambu] Subscribing: device/01S00A292501557/report
2023-02-12 16:21:07.764 DEBUG (Thread-3 (listen_thread)) [custom_components.bambu_lab.pybambu] Sending SUBSCRIBE (d0, m3) [(b'device/01S00A292501557/report', 0)]
2023-02-12 16:21:07.778 DEBUG (Thread-3 (listen_thread)) [custom_components.bambu_lab.pybambu] Received SUBACK
2023-02-12 16:21:09.227 DEBUG (Thread-3 (listen_thread)) [custom_components.bambu_lab.pybambu] Received PUBLISH (d0, q0, r0, m0), 'device/01S00A292501557/report', ...  (144 bytes)
2023-02-12 16:21:09.228 DEBUG (Thread-3 (listen_thread)) [custom_components.bambu_lab.pybambu] b'{"print":{"nozzle_temper":254.96875,"mc_print_line_number":"24872","wifi_signal":"-54dBm","command":"push_status","msg":1,"sequence_id":"3085"}}'
```
I do need to check I haven't broken the initial discovery steps.

**Comment by AdrianGarside** [comment]
Draft PR so you can see what I've changed and comment while I wrap up testing:
https://github.com/greghesp/ha-bambulab/pull/15

**Comment by AdrianGarside** [comment]
Config flow is fine modulo a pre-existing bug with the new tls checkbox.

**Comment by WolfwithSword** [comment]
> So I re-enabled that callback to see what happened and it's just working for me... What was the problem you were seeing?

@AdrianGarside  the issue with the callback was one I ran into. When running Home-Assistant-Core, which is the same as the devContainer setup documented by HA, it causes a huge error that crashes home assistant. Apparently it works fine in HomeAssistant OS.

I tried upgrading the python version too and still the same issue. Commenting out the callback fixed it with seemingly no side effects or concerns.

**Comment by AdrianGarside** [comment]
And you're still seeing that with my latest changes?

**Comment by WolfwithSword** [comment]
Haven't had a chance to rerun it in a while. If you're running the homeassistant dev container (which is HA-Core) and it works on boot, and on brand new integration install/instantiation of a printer and continues working after a reboot then it should be all fine. I have plans to nuke that container and rebuild it before I test again just in case something else is going on with it now.

If you want to really test and the dev container stuff isn't working before I have a chance to (could be 2 weeks 😦 ), could always just download HA-Core via docker and load the custom integration into it and see if it crashes.
