### ISSUE TITLE
[Bug] v2.0.32 incompatible with Raspberry Pi 5 32bit

### ISSUE THREAD

**Issue by hgross** [greghesp/ha-bambulab#717]
### Describe the bug

[This new import ](https://github.com/greghesp/ha-bambulab/compare/v2.0.32...v2.0.33#diff-c90802562624dfd5c6a69fbd9a7527fdfe6911cad985334bd5f15eff21800918R6) in the latest version does not work on a RaspberryPi5 (32bit) 

### To Reproduce

1. Use the official 2024.11.1 ha docker image on a RPI5 32bit system
2. Install ha-bambulab v2.0.32

### Expected Behaviour

ha-bambulab init successful

### What device are you using?

X1CC, P1S

### Diagnostic Output

```shell
Exec format error on initialization


Logger: homeassistant.setup
Quelle: setup.py:334
Erstmals aufgetreten: 21:54:25 (1 Vorkommnisse)
Zuletzt protokolliert: 21:54:25

Setup failed for custom integration 'bambu_lab': Unable to import component: Error loading shared library /usr/local/lib/python3.12/site-packages/curl_cffi/_wrapper.abi3.so: Exec format error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1011, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1071, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/bambu_lab/__init__.py", line 6, in <module>
    from .coordinator import BambuDataUpdateCoordinator
  File "/config/custom_components/bambu_lab/coordinator.py", line 20, in <module>
    from .pybambu import BambuClient
  File "/config/custom_components/bambu_lab/pybambu/__init__.py", line 3, in <module>
    from .bambu_client import BambuClient
  File "/config/custom_components/bambu_lab/pybambu/bambu_client.py", line 19, in <module>
    from .bambu_cloud import BambuCloud
  File "/config/custom_components/bambu_lab/pybambu/bambu_cloud.py", line 6, in <module>
    from curl_cffi import requests
  File "/usr/local/lib/python3.12/site-packages/curl_cffi/__init__.py", line 19, in <module>
    from .__version__ import __curl_version__, __description__, __title__, __version__  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/curl_cffi/__version__.py", line 3, in <module>
    from .curl import Curl
  File "/usr/local/lib/python3.12/site-packages/curl_cffi/curl.py", line 9, in <module>
    from ._wrapper import ffi, lib
ImportError: Error loading shared library /usr/local/lib/python3.12/site-packages/curl_cffi/_wrapper.abi3.so: Exec format error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1031, in async_get_component
    self._component_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1023, in async_get_component
    comp = self._get_component()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1071, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/bambu_lab/__init__.py", line 6, in <module>
    from .coordinator import BambuDataUpdateCoordinator
  File "/config/custom_components/bambu_lab/coordinator.py", line 20, in <module>
    from .pybambu import BambuClient
  File "/config/custom_components/bambu_lab/pybambu/__init__.py", line 3, in <module>
    from .bambu_client import BambuClient
  File "/config/custom_components/bambu_lab/pybambu/bambu_client.py", line 19, in <module>
    from .bambu_cloud import BambuCloud
  File "/config/custom_components/bambu_lab/pybambu/bambu_cloud.py", line 6, in <module>
    from curl_cffi import requests
  File "/usr/local/lib/python3.12/site-packages/curl_cffi/__init__.py", line 19, in <module>
    from .__version__ import __curl_version__, __description__, __title__, __version__  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/curl_cffi/__version__.py", line 3, in <module>
    from .curl import Curl
  File "/usr/local/lib/python3.12/site-packages/curl_cffi/curl.py", line 9, in <module>
    from ._wrapper import ffi, lib
ImportError: Error loading shared library /usr/local/lib/python3.12/site-packages/curl_cffi/_wrapper.abi3.so: Exec format error
```
```


### Log Extracts

```shell
Logger: homeassistant.setup
Quelle: setup.py:334
Erstmals aufgetreten: 21:54:25 (1 Vorkommnisse)
Zuletzt protokolliert: 21:54:25

Setup failed for custom integration 'bambu_lab': Unable to import component: Error loading shared library /usr/local/lib/python3.12/site-packages/curl_cffi/_wrapper.abi3.so: Exec format error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1011, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1071, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/bambu_lab/__init__.py", line 6, in <module>
    from .coordinator import BambuDataUpdateCoordinator
  File "/config/custom_components/bambu_lab/coordinator.py", line 20, in <module>
    from .pybambu import BambuClient
  File "/config/custom_components/bambu_lab/pybambu/__init__.py", line 3, in <module>
    from .bambu_client import BambuClient
  File "/config/custom_components/bambu_lab/pybambu/bambu_client.py", line 19, in <module>
    from .bambu_cloud import BambuCloud
  File "/config/custom_components/bambu_lab/pybambu/bambu_cloud.py", line 6, in <module>
    from curl_cffi import requests
  File "/usr/local/lib/python3.12/site-packages/curl_cffi/__init__.py", line 19, in <module>
    from .__version__ import __curl_version__, __description__, __title__, __version__  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/curl_cffi/__version__.py", line 3, in <module>
    from .curl import Curl
  File "/usr/local/lib/python3.12/site-packages/curl_cffi/curl.py", line 9, in <module>
    from ._wrapper import ffi, lib
ImportError: Error loading shared library /usr/local/lib/python3.12/site-packages/curl_cffi/_wrapper.abi3.so: Exec format error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1031, in async_get_component
    self._component_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1023, in async_get_component
    comp = self._get_component()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1071, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/bambu_lab/__init__.py", line 6, in <module>
    from .coordinator import BambuDataUpdateCoordinator
  File "/config/custom_components/bambu_lab/coordinator.py", line 20, in <module>
    from .pybambu import BambuClient
  File "/config/custom_components/bambu_lab/pybambu/__init__.py", line 3, in <module>
    from .bambu_client import BambuClient
  File "/config/custom_components/bambu_lab/pybambu/bambu_client.py", line 19, in <module>
    from .bambu_cloud import BambuCloud
  File "/config/custom_components/bambu_lab/pybambu/bambu_cloud.py", line 6, in <module>
    from curl_cffi import requests
  File "/usr/local/lib/python3.12/site-packages/curl_cffi/__init__.py", line 19, in <module>
    from .__version__ import __curl_version__, __description__, __title__, __version__  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/curl_cffi/__version__.py", line 3, in <module>
    from .curl import Curl
  File "/usr/local/lib/python3.12/site-packages/curl_cffi/curl.py", line 9, in <module>
    from ._wrapper import ffi, lib
ImportError: Error loading shared library /usr/local/lib/python3.12/site-packages/curl_cffi/_wrapper.abi3.so: Exec format error
```

**Comment by AdrianGarside** [comment]
Can you see if this version helps you get the integration running?
https://github.com/greghesp/ha-bambulab/releases/tag/v2.0.34-dev4

It won't let you use bambu cloud for configuration or for mqtt access but it might at least allow for manually configured direct mqtt connection to the printer.

**Comment by Kiron21** [comment]
RPI3 32bit also.

**Comment by AdrianGarside** [comment]
Can you try the latest version and send me debug logs please.

**Comment by AdrianGarside** [comment]
Specifically https://github.com/greghesp/ha-bambulab/releases/tag/v2.0.35-dev3 as @kanflo spotted and fixed a bug in my attempt to gracefully degrade if curl isn't available.

**Comment by AdrianGarside** [comment]
curl_cffi dev suggested looking at https://piwheels.org/ in https://github.com/lexiforest/curl_cffi/issues/429

@jneilliii also put in the other generic curl_cffi missing issue:

```This might depend on which pi OS version you're using. Just noticed no precompiled builds on piwheels for bookworm.  https://www.piwheels.org/project/curl-cffi/```

For folks hitting problems with their 32bit raspberry pi installs - which pi OS are you running?

**Comment by AdrianGarside** [comment]
> v02.0.34 fixed the issue for me, thanks

You were able to successfully install the integration to a 32 bit raspberry pi?

**Comment by hgross** [comment]
> > v02.0.34 fixed the issue for me, thanks
> 
> You were able to successfully install the integration to a 32 bit raspberry pi and it runs again?

Yes, on a 

- Raspberry Pi 5
- balenaOS 5.3.22 (32bit)
- HA Core 2024.11.1
- HA Frontend 20241106.2

the intialization works again.

There was an unwanted side-effect though. One of the two AMS connected got some entity ids renamed from their previous naming pattern `sensor.x1c_<sn>_ams_2_tray_1` to `sensor.x1c_<sn>_ams_2_slot_1`  (tray -> slot).

**Comment by AdrianGarside** [comment]
And you didn't have to do anything special to unblock yourself? Do the debug logs say anything about curl being unavailable?

" (tray -> slot)" - that's unexpected. I didn't intentionally change that. Although looking 10 months back and they've been 'tray' consistently throughout since at least then. So not sure what happened for you.

**Comment by hgross** [comment]
> And you didn't have to do anything special to unblock yourself? Do the debug logs say anything about curl being unavailable?
> 
> " (tray -> slot)" - that's unexpected. I didn't intentionally change that. Although looking 10 months back and they've been 'tray' consistently throughout since at least then. So not sure what happened for you.

No, I did not unblock anything. But I previously reverted/downgraded from the v2.0.32 version - so there might be leftover pip modules installed? 
I am using an almost unaltered home-assistant docker image ([hoemassistant/home-assistant:2024.11.1](https://hub.docker.com/r/homeassistant/home-assistant/)).

I did find an error message mentioning this special version of curl:
```
2024-11-14 22:26:05.387 ERROR (P1S-Mqtt-41) [custom_components.bambu_lab.pybambu] An exception occurred processing a message:
Traceback (most recent call last):
  File "/config/custom_components/bambu_lab/pybambu/bambu_client.py", line 459, in on_message
    self._device.print_update(data=json_data.get("print"))
  File "/config/custom_components/bambu_lab/pybambu/models.py", line 67, in print_update
    send_event = send_event | self.print_job.print_update(data = data)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bambu_lab/pybambu/models.py", line 465, in print_update
    self._update_task_data()
  File "/config/custom_components/bambu_lab/pybambu/models.py", line 583, in _update_task_data
    self._task_data = self._client.bambu_cloud.get_latest_task_for_printer(self._client._serial)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bambu_lab/pybambu/bambu_cloud.py", line 408, in get_latest_task_for_printer
    data = self.get_tasklist_for_printer(deviceId)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bambu_lab/pybambu/bambu_cloud.py", line 417, in get_tasklist_for_printer
    data = self.get_tasklist()
           ^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bambu_lab/pybambu/bambu_cloud.py", line 394, in get_tasklist
    response = curl_requests.get(url, headers=self._get_headers_with_auth_token(), timeout=10, impersonate=IMPERSONATE_BROWSER)
               ^^^^^^^^^^^^^
NameError: name 'curl_requests' is not defined
```

Speculation: There also could be a fallback to the system-provided curl in the module? 
```
$ curl --version
curl 8.7.1 (armv7-alpine-linux-musleabihf) libcurl/8.7.1 OpenSSL/3.3.1 zlib/1.3.1 brotli/1.1.0 zstd/1.5.6 c-ares/1.28.1 libidn2/2.3.7 libpsl/0.21.5 nghttp2/1.62.0
Release-Date: 2024-03-27
Protocols: dict file ftp ftps gopher gophers http https imap imaps ipfs ipns mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp ws wss
Features: alt-svc AsynchDNS brotli HSTS HTTP2 HTTPS-proxy IDN IPv6 Largefile libz NTLM PSL SSL threadsafe TLS-SRP UnixSockets zstd```

**Comment by AdrianGarside** [comment]
Bambu's cloudflare has relaxed so cloudscraper is working again. I can't promise it'll stay working but for now this switched back to it: https://github.com/greghesp/ha-bambulab/releases/tag/v2.0.37-dev1

**Comment by AdrianGarside** [comment]
Closing for now.
