### ISSUE TITLE
[Bug] ModuleNotFoundError: No module named 'cloudscraper'

### ISSUE THREAD

**Issue by rcode6** [greghesp/ha-bambulab#764]
### Home Assistant Version

2024.11.2

### Bambu Lab Integration Version

v2.0.38 (Issue since v2.0.30 for me)

### Describe the bug

Integration doesn't start properly, System Logs show `ModuleNotFoundError: No module named 'cloudscraper'`

### To Reproduce

Install any 

### Expected Behaviour

Proper integration startup

### What device are you using?

X1C

### Diagnostic Output

```shell
Integration isn't loaded, can't download diagnostics.
```

### Log Extracts

```shell
Setup failed for custom integration 'bambu_lab': Unable to import component: No module named 'cloudscraper'

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1031, in async_get_component
    self._component_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1011, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1071, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/bambu_lab/__init__.py", line 6, in <module>
    from .coordinator import BambuDataUpdateCoordinator
  File "/config/custom_components/bambu_lab/coordinator.py", line 21, in <module>
    from .pybambu import BambuClient
  File "/config/custom_components/bambu_lab/pybambu/__init__.py", line 3, in <module>
    from .bambu_client import BambuClient
  File "/config/custom_components/bambu_lab/pybambu/bambu_client.py", line 19, in <module>
    from .bambu_cloud import BambuCloud
  File "/config/custom_components/bambu_lab/pybambu/bambu_cloud.py", line 7, in <module>
    import cloudscraper
ModuleNotFoundError: No module named 'cloudscraper'
```

### Other Information

I have to downgrade all the way to 2.0.29 to get my integration to start properly.

LAN Mode, and latest docker version of homeassistant.

**Comment by AdrianGarside** [comment]
What is your host OS and how are you running home assistant?

**Comment by rcode6** [comment]
Host OS is TrueNAS Scale.  HomeAssistant is run using the latest docker image as a custom app.

**Comment by AdrianGarside** [comment]
Are there any logs/errors that report an error installing the cloudscraper library when the integration is installed?

**Comment by rcode6** [comment]
When I update/redownload to a newer version, there aren't any errors until I do the required HA restart.  The error above is the first thing that shows up in the error log.

**Comment by AdrianGarside** [comment]
Please try: https://github.com/greghesp/ha-bambulab/releases/tag/v2.0.39-dev1

**Comment by rcode6** [comment]
works perfectly!  thanks for the quick fix!

**Comment by AdrianGarside** [comment]
It may break if/when Bambu amps back up the cloudflare protection. If you're running in LAN mode that probably won't affect you though.
