### ISSUE TITLE
[Bug][Alpha] NoneType' object is not callable

### ISSUE THREAD

**Issue by greghesp** [greghesp/ha-bambulab#90]
### Describe the bug

Latest AMS pre-release update fails to initialise

### To Reproduce

Install

### Expected Behaviour

Working

### What device are you using?

X1C

### Home Assistant Version

2023.4.1

### Component Version

v1.0.4-ams-alpha

### Log Extracts

```
Logger: root
Source: custom_components/bambu_lab/pybambu/models.py:247
Integration: Bambu Lab ([documentation](https://github.com/greghesp/ha-bambulab), [issues](https://github.com/greghesp/ha-bambulab/issues))
First occurred: 09:13:21 (1 occurrences)
Last logged: 09:13:21

Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3591, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1756, in loop_forever
    rc = self._loop(timeout)
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1164, in _loop
    rc = self.loop_read()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1556, in loop_read
    rc = self._packet_read()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 2439, in _packet_read
    rc = self._packet_handle()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3033, in _packet_handle
    return self._handle_publish()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3327, in _handle_publish
    self._handle_on_message(message)
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3570, in _handle_on_message
    on_message(self, self._userdata, message)
  File "/config/custom_components/bambu_lab/pybambu/bambu_client.py", line 174, in on_message
    self._device.update(data=json_data.get("info"))
  File "/config/custom_components/bambu_lab/pybambu/models.py", line 31, in update
    self.ams.update(data)
  File "/config/custom_components/bambu_lab/pybambu/models.py", line 247, in update
    self.device.client.callback("event_ams_info_update")
TypeError: 'NoneType' object is not callable
```

**Comment by AdrianGarside** [comment]
Fixed
